@baseurl = "http://localhost:3333"

# @name create_account
POST @{{baseurl}}/accounts
Content-Type: application/json

{
  "name": "User",
  "email": "eser@email.com",
  "password": "123456"
}


###
# @name authenticate
POST @{{baseurl}}/sessions
Content-Type: application/json

{
  "email": "eser@email.com",
  "password": "123456"
}


